
import { NextPage } from "next";
import Head from "next/head"

import { useRouter } from "next/router";
import { api } from "../../utils/api";
import { useEffect } from "react";
import { ProfileHeader } from "../../components/profile/ProfileHeader";
import { ProfileCard } from "../../components/profile/ProfileCard";
import Link from "next/link";
import { ArrowLeftIcon } from "@heroicons/react/24/solid";
import { useGlobalLoader } from "../../components/shared/Loader";


const ShowProfile: NextPage = () => {
  const router = useRouter()
  const userId = router.query.profile

  const { data, isLoading, refetch } = api.profiles.getProfile.useQuery({ userId: String(userId) });
  const connectAcc = api.profiles.getConnectionAccount.useQuery({ userId: String(userId) });

  const { setLoadingStates } = useGlobalLoader()

  useEffect(() => {
    setLoadingStates([isLoading, connectAcc.isLoading])
  }, [isLoading, connectAcc.isLoading])


  useEffect(() => {
    if (!isLoading) {
      refetch();
    }
  }, [isLoading]);

  if (isLoading) {
    return (
      <>
        <Head>
          <title>Hyper - Profile Page</title>
        </Head>
        <div className="flex justify-between mx-16 pt-8">
          <Link href="/"> <button className="flex btn btn-ghost normal-case gap-2 text-white"><ArrowLeftIcon className="w-4" /> Go Back</button> </Link>
        </div>
        <div className="space-y-4 mx-16 animate-pulse my-4">
          <div className="flex space-x-8">
            <div className="flex justify-center items-start">
              <div className="bg-base-1 rounded-full w-24 h-24" />
            </div>
            <div className="bg-base-1 rounded-xl w-full h-40" />
          </div>
          <div className="bg-base-1 rounded-xl w-full h-80" />
          <div className="bg-base-1 rounded-xl w-full h-40" />
        </div>
      </>
    )
  }


  return (
    <>
      <Head>
        <title>Hyper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-between mx-16 pt-8">
        <Link href="/"> <button className="flex btn btn-ghost normal-case gap-2 text-white"><ArrowLeftIcon className="w-4" /> Go Back</button> </Link>
      </div>

      <div className="mx-16">
        <ProfileHeader data={data} connectAcc={connectAcc} />
        <div className="flex flex-nowrap tabs border-b border-base-4 my-4 overflow-x-auto ">

          <div
            className={`tab tab-lg cursor-pointer text-neutral-0 w-52 border-b-[2px] font-bold border-neutral-0`}
          >
            Overview
          </div>

        </div>
        <ProfileCard connectAcc={connectAcc} />
      </div>
    </>
  );


}

export default ShowProfile
