import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../../utils/api";
import { useRouter } from 'next/router'
import Link from "next/link";
import { EllipsisVerticalIcon, UserCircleIcon } from "@heroicons/react/24/solid"
import { useState } from "react";
import { useSession } from "next-auth/react";
import { UserDetail } from "../../components/shared/Navbar/UserDetail";

const EditProfile: NextPage = () => {

    const router = useRouter()
    const profileMutation = api.profiles.updateProfile.useMutation()

    const [profile, setProfile] = useState({
        username: "",
        countryCode: "",
        bio: ""
    });
    const handleChange = (event: any) => {
        const value = event.target.value;
        setProfile({ ...profile, [event.target.id]: value });
    };


    const saveUpdateProfile = async (e: any) => {
        e.preventDefault();
        profile["countryCode"] = (document.getElementById("countryCode") as HTMLInputElement).value;
        profileMutation.mutate(profile)
        router.push("/profile")
    };


    return (
        <>
            <Head>
                <title>Hyper</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex justify-between px-8 pt-8">
                <Link href="/profile"> <button>← Go Back</button> </Link>
                <button className="btn btn-primary bg-blue-700" onClick={(e) => saveUpdateProfile(e)}>Save Changes</button>
            </div>
            <h1 className="text-4xl font-bold font text-white mx-8 my-4">
                Edit Profile
            </h1>
            <div className="flex flex-row gap-6 px-8 ">
                <div>
                    <UserDetail></UserDetail>
                </div>
                <div className="flex flex-col gap-2 w-full">
                    <div className="form-control w-full ">
                        <label className="label">
                            <span className="label-text">Username</span>

                        </label>
                        <input type="text" id="username"
                            value={profile.username}
                            onChange={(e) => handleChange(e)} placeholder="Type here" className="input input-bordered w-full" />

                    </div>
                    <div className="form-control w-full ">
                        <label className="label">
                            <span className="label-text">Country of Origin</span>

                        </label>
                        <select className="select select-bordered" id="countryCode"
                            name="countryCode">
                            <option disabled selected>Select one</option>
                            <option>en-US</option>
                            <option>id-ID</option>

                        </select>

                    </div>



                </div>
            </div>
            <div className="form-control mx-8 my-4">
                <label className="label">
                    <span className="label-text">Your bio</span>

                </label>
                <textarea className="textarea textarea-bordered h-36" placeholder="Bio" id="bio"
                    value={profile.bio}
                    onChange={(e) => handleChange(e)}></textarea>

            </div>


        </>
    );
};

export default EditProfile;
