import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../../utils/api";
import { useRouter } from 'next/router'
import Link from "next/link";
import React, { useEffect } from "react"
import { useSession } from "next-auth/react"

const Statistic: NextPage = () => {
    const games = api.games.getAll.useQuery()
    const { data, refetch } = api.profiles.getProfile.useQuery()
    const session = useSession()
    const  connectAcc  = api.profiles.getConnectionAccount.useQuery()

    useEffect(() => {
        refetch()
    }, [session])

    const router = useRouter()

    return (
        <>
            <Head>
                <title>Hyper</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex justify-between px-8 pt-8">
                <Link href="/"> <button>← Go Back</button> </Link>
                
                <Link href="/profile/edit"><button className="btn btn-primary bg-blue-700">Edit Profile</button></Link>
             
              
                </div>

            <div className="mx-8">
                <div className="flex flex-row">
                    <div className="basis-[6%] mt-4">
                        <div className="avatar">
                            <div className=" rounded-full">
                                <img src={data?.image} />
                            </div>
                        </div>

                    </div>
                    <div className="basis-[80%] ml-8 mt-4" >
                        <h1 className="text-4xl font-bold font text-white">
                            {data?.username}
                        </h1>

                        <div className="flex flex-row my-4 ">
                            <div className="basis-[5%] ">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Flag_of_the_United_States_%28Pantone%29.svg/1200px-Flag_of_the_United_States_%28Pantone%29.svg.png" className="h-12" />
                            </div>
                            <div className="divider lg:divider-horizontal "></div>
                            <div className="basis-[10%] mr-3 py-3">
                                <div className="badge badge-lg border-none text-neutral-0 font-normal bg-accent-6 text-sm">Casual Gamer</div>
                            </div>
                            <div className="basis-[12%] mr-3 py-3">
                                <div className="badge badge-lg border-none text-neutral-0 font-normal bg-yellow-500 text-sm">Content Creator</div>
                            </div>
                        </div>
                        <h3>{data?.bio}</h3>
                        <div className="flex flex-row my-4">
                            {connectAcc?.data?.map((acc:any) =>
                            <div className="basis-[20%] mr-4">
                                {acc?.name}
                            </div>
                            )}
                            
                        </div>
                    </div>

                </div>


                <div className="tabs my-4 ">
                    <a className="tab tab-bordered tab-active">Overview</a>
                  
                </div>
                
                
                <div className="flex flex-row flex-wrap ">

                    {games?.data?.map(game =>
                        <div key={game.id} className="card bg-base-2 shadow-xl m-4 grid  flex-grow rounded-box " onClick={() => router.push(`/result?${game.id}`)}>
                            <div className="card-body gap-4 lg:gap-0">

                                <div className="flex flex-row gap-6">
                                    <figure>
                                        <img className="bg-white rounded-md w-16 h-16" src={game.logoUrl} />
                                    </figure>

                                    <div className="flex flex-col gap-2">
                                        <h2 className="card-title text-neutral-0 font-bold">{game.name}</h2>
                                        <div className="flex flex-col sm:flex-row gap-4">

                                        <div className="flex flex-row items-center gap-2">
                                           
                                            <div className="badge badge-lg border-none text-neutral-0 font-normal bg-blue-500 text-sm">First-Person Shooter</div>
                                        </div>

                                        <div className="flex flex-row items-center gap-2">
                                            <div className="badge badge-lg border-none text-neutral-0 font-normal bg-accent-6 text-sm">Competitive</div>
                                        </div>

                                    </div>
                                        
                                    </div>
                                </div>

                            </div>
                        </div>

                    )}

                </div>

            </div>
        </>
    );
};

export default Statistic;
