import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../../utils/api";
import { useRouter } from 'next/router'
import Link from "next/link";
import React, { useEffect } from "react"
import { useSession } from "next-auth/react"
import { ArrowLeftIcon, PencilSquareIcon } from "@heroicons/react/24/solid"

const Statistic: NextPage = () => {

    const { data, refetch } = api.profiles.getProfile.useQuery()
    const session = useSession()
    
    useEffect(() => {
        refetch()
    }, [session])

    const router = useRouter()

    return (
        <>
            <Head>
                <title>Hyper</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex justify-between mx-16 pt-8">
            <Link href="/"> <button className="flex btn btn-ghost normal-case gap-2 text-white"><ArrowLeftIcon className="w-4"/> Go Back</button> </Link>

            <Link href="/profile/edit"><button className="btn btn-primary bg-blue-700 normal-case flex gap-2 text-white"><PencilSquareIcon className="w-4"/>Edit Profile</button></Link>


            </div>

            <div className="mx-16">
                <div className="flex flex-col sm:flex-row gap-4">
                    <div className=" mt-4">
                        <div className="avatar">
                            <div className=" rounded-full h-24 w-24">
                                <img src={data?.image} />
                            </div>
                        </div>

                    </div>
                    <div className=" ml-8 mt-4" >
                        <h1 className="text-4xl font-bold font text-white">
                            {data?.username}
                        </h1>
                        <div className="flex flex-col sm:flex-row gap-4 mt-4">
                            <div className="flex flex-col sm:flex-row ">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Flag_of_the_United_States_%28Pantone%29.svg/1200px-Flag_of_the_United_States_%28Pantone%29.svg.png" className="h-10 w-16" />
                                <div className="divider lg:divider-horizontal "></div>
                                <div className="flex flex-row items-center gap-2">
                                <div className="badge badge-lg border-none text-neutral-0 font-normal bg-accent-6 text-sm">Casual Gamer</div>
                            </div>
                            </div>
                            

                            <div className="flex flex-row items-center gap-2">
                                <div className="badge badge-lg border-none text-neutral-0 font-normal bg-yellow-500 text-sm">Content Creator</div>
                            </div>

                        </div>

                        <h3 className="mt-4 text-white">{data?.bio}</h3>
                        
                    </div>

                </div>


                <div className="tabs my-4 ">
                    <a className="tab tab-bordered tab-active">Overview</a>

                </div>


                

            </div>
        </>
    );
};

export default Statistic;
