Project hyper_party_system {
  database_type: 'PostgreSQL'
  Note: 'The Social Media Platform for Gamers'
}

table User {
  id string [primary key]
  name string
  profileImage string
  
  Note: "Stores core user data"
}

table Game {
  id string [pk]
  name string [not null]

  Note: "Stores game data. Should be pre-filled with data for VALORANT and Apex/CSGO in MVP"
}

table GameAccount {
  userId string [not null]
  gameId string [not null]
  
  gameIdentifier string [not null]

  createdAt datetime [default: "now()"]
  indexes {
    (userId, gameId) [pk]
    gameIdentifier [unique]
  }

  Note: "Stores integrated user game accounts"
}

Ref: GameAccount.gameId > Game.id
Ref: GameAccount.userId > User.id

table Party {
  id string [pk]
  gameId string
  discordInviteLink string

  Note: "Stores party metadata"
}

Ref: Party.gameId > Game.id

table PartyMember {
  userId string
  partyId string
  gameId string
  level PartyMemberLevel

  indexes {
    (userId, partyId) [pk]
  }

  Note: "Stores details about a joined PartyMember"
}

enum PartyMemberLevel {
  member
  leader
}

Ref: PartyMember.(userId, gameId) > GameAccount.(userId, gameId)
Ref: PartyMember.partyId > Party.id
