import { type NextPage } from "next";
// import { signIn, useSession } from "next-auth/react";
// import { api } from "../../utils/api";

import Head from "next/head";

// Temporary
import { status, accountData, mmrData, competitiveHistory } from "../../../public/temp/message.json"
import { ValorantStatistic } from "../../components/PlayerStatistics/ValorantStatistic";

const Statistic: NextPage = () => {

    return (
        <>
            <Head>
                <title>Hyper</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="m-8 ">
                
                <ValorantStatistic status={status} accountData={accountData} mmrData={mmrData} competitiveHistory={competitiveHistory}></ValorantStatistic>
 
            </div>
        </>
    );
};

export default Statistic;
