import { type NextPage } from "next";
// import { signIn, useSession } from "next-auth/react";
// import { api } from "../../utils/api";
import { ValorantStatistic } from "../../components/PlayerStatistics/ValorantStatistic";
import { ValorantMatchDetail } from "../../components/PlayerStatistics/ValorantMatchDetail";
import Head from "next/head";

// Temporary
import { status, accountData, mmrData, competitiveHistory } from "../../../public/temp/message.json"
import { status1, map_name, friendly_team_score, enemy_team_score, friendly_team_members, enemy_team_members } from "../../../public/temp/match.json"


const Statistic: NextPage = () => {


    return (
        <>
            <Head>
                <title>Hyper</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="m-8 "> 

                <ValorantMatchDetail status={status1} map_name={map_name} friendly_team_score={friendly_team_score} enemy_team_score={enemy_team_score} friendly_team_members={friendly_team_members} enemy_team_members={enemy_team_members} />
 
            </div>
        </>
    );
};

export default Statistic;
