import { type NextPage } from "next";
import Head from "next/head";



const Statistic: NextPage = () => {

    return (
        <>
            <Head>
                <title>Hyper</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="m-8 ">
                <div className="flex flex-row">
                    <div className="basis-[10%] bg-red-300">
                    <img src="https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/bltc3bf97021e2b2130/63b8afcc438f80612c39678d/Valorant_2022_EP6-1_PlayVALORANT_PlayValorantHomepage_3440x1020_MB01.png.jpg" className="rounded-lg" />
                    </div>
                    <div className="basis-[35%] ml-8" >
                        <h1 className="text-4xl font-bold font text-white">
                            Rostova#5722
                        </h1>
                        <h1 className="text-4xl font-bold font">
                            Rostova#5722
                        </h1>
                    </div>

                </div>
                
       
                <div className="tabs my-8">
                    <a className="tab tab-lifted">Tab 1</a>
                    <a className="tab tab-lifted tab-active">Tab 2</a>
                    <a className="tab tab-lifted">Tab 3</a>
                </div>
                <div className="flex w-full">
                    <div className="grid h-20 flex-grow card bg-base-300 rounded-box place-items-center">content</div>
                    <div className="divider-horizontal"></div>
                    <div className="grid h-20 flex-grow card bg-base-300 rounded-box place-items-center">content</div>
                </div>
            </div>
        </>
    );
};

export default Statistic;
