import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import NavWrapper from "../components/shared/Navbar";

const Home: NextPage = () => {
  const games = api.games.getAll.useQuery()
  console.log(games?.data)

  return (
    <>
      <Head>
        <title>Hyper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavWrapper>
        <div className="hero min-h-screen pt-16" style={{ backgroundImage: 'url(/hero-1.png)' }}>
          <div className="hero-overlay bg-black bg-opacity-50" />
          <div className="hero-content text-center flex flex-col">
            <h1 className="text-white font-bold text-2xl">
              The only gaming social platform worth using.
            </h1>
            <p className="text-white font-mono">
              Gaming <span className="font-bold">communities</span> and <span className="font-bold">party-finding</span> made easy. Join Hyper to level up your game, Together.
            </p>

            <div className="mt-4 space-y-4">
              <p className="text-gray-100 font-mono">
                Active Communities
              </p>

              <div className="grid grid-cols-2 gap-y-6 gap-x-8">
                {games?.data?.map((item) => (
                  <div key={item.id} className="flex items-center justify-center">
                    <img className="h-16" src={item.logoUrl} />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </NavWrapper>
    </>
  );
};

export default Home;

