import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";

import { api } from "../utils/api";


const Home: NextPage = () => {

  const games = api.games.getAll.useQuery()
  const session = useSession()

  return (
    <>
      <Head>
        <title>Hyper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div>
        {
          session.status === "authenticated" ? (

            <div className="p-8 md:p-16">

              <div className="flex flex-row space-x-4 items-center pb-8">
                <img src="/white-logo-only.svg" className="h-12 md:h-16" />
                <h1 className="font-bold text-neutral-0 text-2xl md:text-4xl">Welcome to Hyper</h1>
              </div>

              <div className="flex flex-col md:grid md:grid-cols-2">

                {games?.data?.map(game => 

                  <div key={game.id} className="card bg-base-2 shadow-xl m-4">
                    <div className="card-body gap-4 lg:gap-2">

                      <div className="flex flex-row gap-4">
                        <figure>
                          <img className="bg-white rounded-md w-16 h-16" src={game.logoUrl} />
                        </figure>
                      
                        <div className="flex flex-col gap-2">
                          <h2 className="card-title text-neutral-0 font-bold">{game.name}</h2>
                          <div className="badge badge-lg border-none text-neutral-0 font-normal bg-accent-6 text-sm">Games</div>
                        </div>
                      </div>
                      
                      <div className="card-actions flex justify-between items-center">
                        <div className="flex flex-col sm:flex-row gap-4">

                          <div className="flex flex-row items-center gap-2 md:py-[12px]">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="stroke-2 stroke-success-main w-6 h-6">
                              <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                              <path stroke-linecap="round" stroke-linejoin="round" d="M15.91 11.672a.375.375 0 010 .656l-5.603 3.113a.375.375 0 01-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112z" />
                            </svg>
                            <p className="font-normal font-sm text-base-5">0 Open Parties</p>
                          </div>

                          <div className="flex flex-row items-center gap-2 md:py-[12px]">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="stroke-2 stroke-success-main w-6 h-6">
                              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
                            </svg>
                            <p className="font-normal font-sm text-base-5">{game.communityPosts.length} Community Posts</p>
                          </div>

                        </div>

                        <button className="btn btn-ghost gap-2">
                          View More
                          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-4 h-4"> 
                            <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                          </svg>
                        </button>
                      </div>

                    </div>
                  </div>

                )}

              </div>

              <div className="flex flex-col w-full items-center content-center justify-center py-16 gap-y-4">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="stroke-1 stroke-base-3 w-24 h-24">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M20.893 13.393l-1.135-1.135a2.252 2.252 0 01-.421-.585l-1.08-2.16a.414.414 0 00-.663-.107.827.827 0 01-.812.21l-1.273-.363a.89.89 0 00-.738 1.595l.587.39c.59.395.674 1.23.172 1.732l-.2.2c-.212.212-.33.498-.33.796v.41c0 .409-.11.809-.32 1.158l-1.315 2.191a2.11 2.11 0 01-1.81 1.025 1.055 1.055 0 01-1.055-1.055v-1.172c0-.92-.56-1.747-1.414-2.089l-.655-.261a2.25 2.25 0 01-1.383-2.46l.007-.042a2.25 2.25 0 01.29-.787l.09-.15a2.25 2.25 0 012.37-1.048l1.178.236a1.125 1.125 0 001.302-.795l.208-.73a1.125 1.125 0 00-.578-1.315l-.665-.332-.091.091a2.25 2.25 0 01-1.591.659h-.18c-.249 0-.487.1-.662.274a.931.931 0 01-1.458-1.137l1.411-2.353a2.25 2.25 0 00.286-.76m11.928 9.869A9 9 0 008.965 3.525m11.928 9.868A9 9 0 118.965 3.525" />
                </svg>
                <h1 className="font-bold text-base-3 text-xl text-center">More games will be supported soon</h1>
              </div>
              


            </div>

          ) : (

            <div className="flex flex-col gap-y-8 content-center items-center p-8 py-16 md:p-24">
              <img src="/white-logo-only.svg" className="h-20" />

              <div className="flex flex-col gap-y-4 items-center">
                <h1 className="font-bold text-neutral-0 text-4xl text-center">Welcome to Hyper</h1>
                <p className="text-base-4 text-sm text-center">Please connect with Discord before using our services</p>
              </div>
              

              <button className="btn bg-other-discord font-bold gap-2" onClick={() => signIn()}>
                <div className="bg-neutral-0 rounded-full text-other-discord w-6 h-6 flex justify-center items-center">
                  <svg className="fill-current w-4 h-4" width="13" height="10" viewBox="0 0 13 10" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10.76 1.15175C9.98051 0.794153 9.13654 0.534605 8.25739 0.384644C8.23981 0.384644 8.22809 0.390411 8.21636 0.401947C8.11087 0.592282 7.98779 0.840295 7.90573 1.03063C6.96212 0.892204 6.0185 0.892204 5.09247 1.03063C5.01041 0.834527 4.88733 0.592282 4.77598 0.401947C4.77012 0.390411 4.75253 0.384644 4.73495 0.384644C3.8558 0.534605 3.01769 0.794153 2.23232 1.15175C2.22646 1.15175 2.22059 1.15752 2.21473 1.16329C0.62055 3.51076 0.180978 5.79478 0.397834 8.05573C0.397834 8.06727 0.403695 8.07881 0.415416 8.08457C1.47039 8.84591 2.48434 9.30733 3.48656 9.61302C3.50415 9.61879 3.52173 9.61302 3.52759 9.60149C3.76203 9.28426 3.97302 8.94973 4.15471 8.5979C4.16644 8.57483 4.15471 8.55176 4.13127 8.54599C3.79719 8.4191 3.4807 8.26914 3.17007 8.09611C3.14663 8.08457 3.14663 8.04997 3.16421 8.03266C3.22868 7.98652 3.29315 7.93461 3.35762 7.88847C3.36934 7.87693 3.38693 7.87693 3.39865 7.8827C5.41482 8.78824 7.58924 8.78824 9.58197 7.8827C9.59369 7.87693 9.61127 7.87693 9.623 7.88847C9.68747 7.94038 9.75194 7.98652 9.81641 8.03843C9.83985 8.05573 9.83985 8.09034 9.81055 8.10188C9.50578 8.28068 9.18342 8.42487 8.84935 8.55176C8.8259 8.55753 8.82004 8.58637 8.8259 8.60367C9.01346 8.9555 9.22445 9.29003 9.45303 9.60726C9.47061 9.61302 9.48819 9.61879 9.50578 9.61302C10.5139 9.30733 11.5278 8.84591 12.5828 8.08457C12.5945 8.07881 12.6004 8.06727 12.6004 8.05573C12.8582 5.44295 12.1725 3.17623 10.7835 1.16329C10.7776 1.15752 10.7717 1.15175 10.76 1.15175ZM4.45948 6.67725C3.8558 6.67725 3.35176 6.12931 3.35176 5.45448C3.35176 4.77966 3.84408 4.23172 4.45948 4.23172C5.08075 4.23172 5.57307 4.78543 5.56721 5.45448C5.56721 6.12931 5.07489 6.67725 4.45948 6.67725ZM8.54458 6.67725C7.9409 6.67725 7.43686 6.12931 7.43686 5.45448C7.43686 4.77966 7.92918 4.23172 8.54458 4.23172C9.16584 4.23172 9.65816 4.78543 9.6523 5.45448C9.6523 6.12931 9.16584 6.67725 8.54458 6.67725Z" fill="current" />
                  </svg>
                </div>
                <p className="font-bold text-neutral-0">Connect Discord</p>
              </button>
            </div>
            

          )

        }
      </div>
    </>
  );
};

export default Home;

