import { type NextPage } from "next";
import Head from "next/head";

import NavWrapper from "../components/shared/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hyper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;

