import { type NextPage } from "next";
import Head from "next/head";
import Image from 'next/image'

import { api } from "../../utils/api";

const Home: NextPage = () => {
  const games = api.games.getAll.useQuery()
  console.log(games?.data)

  return (
    <>
      <Head>
        <title>Hyper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="flex flex-row flex-wrap p-16">

        {games?.data?.map(game => 

          <div key={game.id} className="card w-96 bg-base-100 shadow-xl m-4">
          <figure><img className="bg-white rounded-md w-6 h-6" src={game.logoURL} /></figure>
          <div className="card-body">
            <h2 className="card-title">{game.name}</h2>
            <p>Description</p>
            <div className="card-actions justify-end">
              <button className="btn btn-primary">Watch</button>
            </div>
          </div>
        </div>

        )}

        </div>
    </>
  );
};

export default Home;

