import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../../utils/api";
import NavWrapper from "../../components/shared/Navbar";

const Home: NextPage = () => {
  const games = api.games.getAll.useQuery()
  console.log(games?.data)

  return (
    <>
      <Head>
        <title>Hyper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavWrapper>
        <div>
        <div className="card card-side bg-base-100 shadow-xl">
          <figure></figure>
          <div className="card-body">
            <h2 className="card-title">New movie is released!</h2>
            <p>Click the button to watch on Jetflix app.</p>
            <div className="card-actions justify-end">
              <button className="btn btn-primary">Watch</button>
            </div>
          </div>
        </div>
        </div>
      </NavWrapper>
    </>
  );
};

export default Home;

