import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../../utils/api";
import NavWrapper from "../../components/shared/Navbar";

const Home: NextPage = () => {
  const games = api.games.getAll.useQuery()
  console.log(games?.data)

  return (
    <>
      <Head>
        <title>Hyper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavWrapper>
        
      </NavWrapper>
    </>
  );
};

export default Home;

