import { type NextPage } from "next"
import Head from "next/head"
import { api } from "../../../utils/api"
import { useRouter } from 'next/router'
import Link from "next/link"
import React, { useState } from "react"
import { useSession } from "next-auth/react"
import { ArrowLeftIcon, EyeIcon, FolderPlusIcon, LinkIcon, PaperAirplaneIcon } from "@heroicons/react/24/solid"
import { CommunityPostStatus } from "@prisma/client"

const CreateGuides: NextPage = () => {
  const router = useRouter()
  const gameId = router.query.game
  const postMutation = api.guides.create.useMutation()

  const [post, setPost] = useState({
    type: null,
    status: null,
    title: "",
    content: "",
    headerType: null,
    headerUrl: "",
    gameId: gameId,
  })

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value
    setPost({
      ...post,
      [event.target.id]: value,
    })
  }

  const savePost = (event: React.MouseEventHandler<HTMLButtonElement>, status: CommunityPostStatus) => {
    
  }

  return (
    <>
      <Head>
        <title>Create Guide</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col gap-6">
        <div className="flex justify-between px-8 pt-8">
          <Link href="/"> <button className="flex btn btn-ghost normal-case gap-2"><ArrowLeftIcon className="w-4"/> Go Back</button> </Link>
          <div className="flex justify-between gap-2">
            <button className="flex btn btn-ghost normal-case gap-2"><FolderPlusIcon className="w-4"/> Save as Draft</button>
            <button className="flex btn btn-ghost normal-case gap-2"><EyeIcon className="w-4"/> Save & Preview</button>
            <button className="flex btn btn-primary bg-blue-700 normal-case gap-2"><PaperAirplaneIcon className="w-4"/> Save Changes</button>
          </div>
        </div>

        <div className="form-control w-full px-8">
          <label className="label">
            <span className="label-text">Post Title</span>
          </label>
          <input type="text" placeholder="How to Win a match" className="input input-bordered w-full" />
        </div>

        <div className="flex justify-between px-8 gap-6">
          <div className="form-control w-1/4">
            <label className="label">
              <span className="label-text">Header Attachment Type</span>
            </label>
            <select className="select w-full">
              <option disabled selected>Select header type</option>
              <option>Image</option>
              <option>Video</option>
            </select>
            <label className="label">
              <span className="label-text-alt">Please select the attachment type</span>
            </label>
          </div>

          <div className="form-control w-3/4">
            <label className="label">
              <span className="label-text">Header Attachment Link</span>
            </label>
            <label className="input-group">
              <span><LinkIcon className="w-4"/></span>
              <input type="text" placeholder="www.medal.tv/001ojiad0983q09" className="input input-bordered w-full" />
            </label>
            <label className="label">
              <span className="label-text-alt">Only supports link or files provided by selected attachment type</span>
            </label>
          </div>
        </div>

        <div className="form-control w-full px-8">
          <label className="label">
            <span className="label-text">Select Post Type</span>
          </label>
          <select className="select w-full">
            <option disabled selected>Select post type</option>
            <option>Clip</option>
            <option>Guide</option>
          </select>
        </div>

        <div className="form-control w-full px-8">
          <label className="label">
            <span className="label-text">Post Content</span>
          </label>
          <textarea className="textarea" placeholder="This post contains a match replay and ..."></textarea>
        </div>

      </div>

      
    </>
  )
}

export default CreateGuides
